<?xml version="1.0" ?>
<robot name="differential_bot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find mpc_model_description)/urdf/common/common_properties.xacro"/>
  <xacro:include filename="$(find mpc_model_description)/urdf/diff/differential_bot.gazebo.xacro"/>

<!-- base -->

<link name="base_footprint"/>

 <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 ${M_PI*0.5}"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="-0 0 0.2465" rpy="0 0 ${-M_PI*0.5}"/>
      <geometry>
        <box size="0.265 0.265 0.089"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="0 0.064  0.048" rpy="0 0 ${M_PI*0.5}"/>
      <geometry>
        <box size="0.265 0.265 0.089"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0.064 0.048" rpy="0 0 ${M_PI*0.5}"/>
      <mass value="0.01"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04" 
               iyy="8.6195418e-03" iyz="-3.5422299e-06" 
               izz="1.4612727e-02" /> 
    </inertial>
  </link>

<!-- chassis -->

  <xacro:property name="chassis_length" value="0.258"/>
  <xacro:property name="chassis_width" value="0.168"/>
  <xacro:property name="chassis_height" value="0.02"/>
  <xacro:property name="chassis_mass" value="2.788"/>

  <link name="chassis">
    <visual>
      <origin xyz="0 0 ${-chassis_height / 2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="chassis_mat"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${-chassis_height / 2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_link_to_chasis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint>

  <link name="left_steering_link" />
  
  <joint name="left_steering_joint" type="revolute">
    <parent link="left_steering_link"/>
    <child link="left_front_axle_carrier"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-degrees_45}" upper="${degrees_45}"
            effort="${servo_stall_torque}" velocity="${servo_no_load_speed}"/>
  </joint>

  <transmission name="left_steering_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_steering_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_steering_act">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="left_front_axle_carrier" />

  <joint name="left_front_axle" type="continuous">
    <parent link="left_front_axle_carrier"/>
    <child link="left_front_wheel"/>
    <origin rpy="${degrees_90} 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit effort="${axle_eff_limit}" velocity="${axle_vel_limit}"/>
  </joint>
  
  <transmission name="left_front_axle_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_front_axle">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_front_axle_act">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="left_front_wheel">
    <visual>
      <origin xyz="0
                    ${lr_reflect * (axle_length - (tire_width / 
                    2 - hex_hub_depth))}
                    0"/>
      <geometry>
        <cylinder radius="${tire_dia / 2}" length="${tire_width}"/>
      </geometry>
      <material name="tire_mat"/>
    </visual>

    <collision>
      <origin xyz="0
                    ${lr_reflect * (axle_length - (tire_width / 
                    2 - hex_hub_depth))}
                    0"/>
      <geometry>
        <cylinder radius="${tire_dia / 2}" length="${tire_width}"/>
      </geometry>
    </collision>

  </link>

  <joint name="left_front_shock" type="prismatic">
    <parent link="chassis"/>
    <child link="${child}"/>

    <origin xyz="${fr_reflect * wheelbase / 2}
                  ${lr_reflect * ((hex_hub_dist / 2) - axle_length)}
                  ${(wheel_travel / 2) - shock_z_offset}"/>
    <axis xyz="0 0 -1"/>
    <limit lower="${-wheel_travel / 2}" upper="${wheel_travel / 2}"
            effort="${shock_eff_limit}" velocity="${shock_vel_limit}"/>
  </joint>

  <transmission name="left_front_shock_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_front_shock">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_front_shock_act">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

<!-- imu -->

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 -0.07 0.37" rpy="0 0 ${-M_PI*0.5}"/>
  </joint>

  <link name="imu_link"/>


<!-- scan -->

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 -0.28 0.21" rpy="0 0 ${-M_PI*0.5}"/>
  </joint>

  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mpc_model_description/meshes/lidar.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
  </link>
</robot>